<script lang="ts">
 import {app} from '../../state/app.svelte';import {mappingNames,type Mapping} from '../../types/bridge';
 import {stateText,number,providerText} from '../../format';import Icon from '../Icon.svelte';
 const essentials:Mapping[]=['prompt','send','response','model','reasoning','stop','new_chat','attachment'];
 const active=$derived(app.sessions.find(s=>s.provider===app.provider?.id&&s.status==='ACTIVE'));
</script>
<aside class="inspector" aria-label="Connection inspector">
 <div class="inspector-head"><div class="inspector-tabs"><button class:active={app.inspectorTab==='connection'} onclick={()=>app.inspectorTab='connection'}>Connection</button><button class:active={app.inspectorTab==='browser'} onclick={()=>app.inspectorTab='browser'}>Browser</button></div><button class="icon-button" aria-label="Close inspector" onclick={()=>{app.inspectorVisible=false;app.saveLayout();}}><Icon name="close" size={14}/></button></div>
 {#if app.provider}
  {@const p=app.provider}
  {#if app.inspectorTab==='connection'}
   <div class="inspector-section"><span class="label">Website connector</span><div class="connection-title"><h2>{p.label}</h2><span class="dot" class:online={p.state==='READY'} class:busy={p.active}></span></div><span class="tag" class:ready={p.state==='READY'} class:attention={p.state==='RATE_LIMITED'||p.state==='BROKEN_MAPPING'}>{p.active?'Generating':providerText(p)}</span><p style="margin-top:12px">{p.state==='READY'?'Available to clients on your local gateway.':p.state==='LOGIN_REQUIRED'?'Sign in on the website. Account credentials stay in this browser profile.':p.state==='RATE_LIMITED'?'The website reported a usage limit. No automatic retry is sent.':'Use the website normally, then rescan or pick a control to finish connecting.'}</p></div>
   <div class="inspector-section"><label class="field"><span>Default client model</span><select aria-label="Default client model" value={app.preferences.default_model} onchange={event=>app.settings({default_model:event.currentTarget.value})}><option value="">Select a default…</option>{#each app.models as model(model.id)}<option value={model.id}>{model.provider.label} / {model.display_name}</option>{/each}</select></label><dl class="metadata-list"><dt>Models discovered</dt><dd>{p.models.length}</dd><dt>Context window</dt><dd>{p.context_hint?`${number(p.context_hint)} · user set`:'Unknown'}</dd><dt>Token accounting</dt><dd>Estimated</dd><dt>Tool calls</dt><dd>Text bridge</dd><dt>Connector version</dt><dd class="mono">{String(p.mapping_version).padStart(3,'0')}</dd></dl></div>
   <div class="inspector-section"><div class="section-title"><h3>Page controls</h3><small>Click to remap</small></div>{#each essentials as role(role)}<button class="mapping-row" disabled={p.active} title={`Pick ${mappingNames[role]} on the website`} onclick={()=>app.pick(role)}><span><Icon name={p.mappings[role]>0?'check':'plus'} size={12}/>{mappingNames[role]}</span><span class="mapping-node">{p.mappings[role]>0?'Mapped':'Not found'}</span></button>{/each}<button class="secondary wide" style="margin-top:13px;font-size:11px" disabled={p.active} onclick={()=>app.perform('provider.rescan',{provider_id:p.id})}><Icon name="scan" size={14}/>Rescan page</button></div>
   <div class="inspector-section"><h3>Conversation</h3>{#if active}<dl class="metadata-list"><dt>Session</dt><dd class="mono">{active.id.slice(-12)}</dd><dt>Completed turns</dt><dd>{active.turn_count}</dd></dl><button class="secondary wide" style="margin-top:14px" onclick={()=>app.cancel(active.id)}><Icon name="stop" size={13}/>Stop generation</button>{:else}<p>No request running. A connected client can start a conversation without leaving this website.</p>{/if}<button class="text-button wide" style="margin-top:10px;font-size:11px;justify-content:space-between" onclick={()=>app.navigate('sessions')}>View sessions<Icon name="arrow" size={12}/></button></div>
   <div class="inspector-section" style="border:0"><p class="notice-small">A mapped control is an observation, not a guarantee of model capability. Unknown limits stay unknown.</p></div>
  {:else}
   <div class="inspector-section"><h3>Page</h3><div class="control-list"><button onclick={()=>app.perform('provider.home',{provider_id:p.id})} disabled={p.active}><Icon name="home" size={15}/>Go to provider home</button><button onclick={()=>app.control('external')}><Icon name="external" size={15}/>Open in default browser</button><button onclick={()=>{app.findVisible=true;}}><Icon name="search" size={15}/>Find on page<kbd>Ctrl F</kbd></button><button onclick={()=>app.clipboard(p.current_url||p.url)}><Icon name="copy" size={15}/>Copy page URL</button></div><div class="inline" style="justify-content:space-between;margin-top:16px"><span class="muted">Page zoom</span><div class="button-group"><button class="icon-button" aria-label="Zoom out" onclick={()=>app.control('zoom_out')}>−</button><button class="text-button" title="Reset zoom" onclick={()=>app.control('zoom_reset')}>{app.zoom}%</button><button class="icon-button" aria-label="Zoom in" onclick={()=>app.control('zoom_in')}>+</button></div></div></div>
   <div class="inspector-section"><h3>Explicit website permissions</h3><p style="margin-bottom:12px">Each permission expires after one use or 60 seconds. Downloads never run automatically.</p><div class="control-list"><button class="secondary" onclick={()=>app.control('popup_once')}><Icon name="external" size={15}/>Allow one sign-in popup</button><button class="secondary" onclick={()=>app.control('download_once')}><Icon name="download" size={15}/>Allow one download</button></div></div>
   <div class="inspector-section"><h3>Profile</h3><div class="control-list"><button onclick={()=>app.perform('provider.update',{provider_id:p.id,pinned:!p.pinned})}><Icon name="pin" size={15}/>{p.pinned?'Allow sleeping when idle':'Keep this website awake'}</button><button onclick={()=>app.showPopup('clear-profile',p.id)}><Icon name="refresh" size={15}/>Clear website storage</button><button onclick={()=>app.closeProvider(p.id)}><Icon name="close" size={15}/>Close this tab</button></div></div>
   <div class="inspector-section"><h3>Developer tools</h3><p style="margin-bottom:10px">Page inspection is restricted to developer mode. Provider pages cannot open desktop commands.</p><button class="secondary wide" disabled={!app.preferences.developer_mode} onclick={()=>app.control('inspect')}><Icon name="terminal" size={14}/>Toggle page inspector</button><button class="text-button wide" onclick={()=>app.navigate('detector')}>Open detector lab<Icon name="arrow" size={13}/></button></div>
  {/if}
 {:else}<div class="inspector-section"><h3>A local connection, not another account</h3><p>Add a website, sign in normally, then connect a client to the local gateway. No provider API key is required.</p><hr/><p>The browser stays at the center. Connection details and page controls live here when you open a website.</p></div>{/if}
</aside>
