<script lang="ts">
 import {app} from '../lib/state/app.svelte';import * as bridge from '../lib/api/bridge';import type {Evidence,Mapping} from '../lib/types/bridge';import {mappingNames} from '../lib/types/bridge';import Icon from '../lib/components/Icon.svelte';
 let evidence=$state<Evidence|null>(null),manual=$state(''),loading=$state(false);let requestVersion=0;
 const roles=Object.keys(mappingNames) as Mapping[];let choices=$state<Partial<Record<Mapping,string>>>({});
 const controls=$derived(evidence?.controls??[]);
 $effect(()=>{const id=app.provider?.id,version=app.provider?.mapping_version;void version;const ticket=++requestVersion;if(!id){evidence=null;return;}loading=true;
  void bridge.request<Evidence|null>('detector.evidence',{provider_id:id}).then(result=>{if(ticket===requestVersion){evidence=result;choices={};}}).catch(error=>{if(ticket===requestVersion)app.error=String(error);}).finally(()=>{if(ticket===requestVersion)loading=false;});
 });
 async function record(role:Mapping){if(!app.provider||!evidence||!choices[role])return;await app.perform('connector.record',{provider_id:app.provider.id,document_id:evidence.document_id,mapping:role,node:Number(choices[role])});}
 async function exportConnector(){if(!app.provider)return;const data=await app.perform('connector.export',{provider_id:app.provider.id});if(data!==undefined)await app.export(`bridge-connector-${app.provider.id}.json`,data);}
 async function importConnector(){if(!app.provider)return;try{const data=await bridge.importDocument();if(data)await app.perform('connector.import',{provider_id:app.provider.id,connector:data});}catch(error){app.error=String(error);}}
</script>
<section class="screen"><div class="screen-inner"><header class="screen-head"><div><div class="breadcrumb">Workspace / Discovery</div><h1>Detector lab</h1><p>Inspect the evidence, repair a mapping, or export a reusable connector.</p></div><select aria-label="Inspect website" value={app.selectedProvider??''} onchange={event=>app.selectedProvider=Number(event.currentTarget.value)||null}><option value="">Choose a website</option>{#each app.providers as p}<option value={p.id}>{p.label}</option>{/each}</select></header>
{#if app.provider}{@const p=app.provider}<div class="filterbar"><span class="tag"><Icon name="scan" size={14}/>Symbolic detector</span><span class="count">MAPPING {p.mapping_version}</span><span class="spacer"></span><button class="text-button" disabled={p.active} onclick={importConnector}><Icon name="upload" size={13}/>Import</button><button class="text-button" onclick={exportConnector}><Icon name="download" size={13}/>Export</button><button class="secondary" disabled={p.active||loading} onclick={()=>app.perform('provider.rescan',{provider_id:p.id})}><Icon name="refresh" size={13}/>Rescan page</button></div>
<div class="lab-columns" style="margin-top:26px"><div><div class="section-title"><h2>Control mappings</h2><small>{controls.length} observed elements</small></div><p class="field-hint" style="margin-bottom:13px">Pick a control on the website or select an observed element. The backend validates its role and rejects sensitive fields.</p><table class="mapping-table"><thead><tr><th>OPERATION</th><th>OBSERVED ELEMENT</th><th></th></tr></thead><tbody>{#each roles as role(role)}<tr><td><span class="inline" style="gap:7px"><Icon name={p.mappings[role]?'check':'plus'} size={12}/>{mappingNames[role]}</span></td><td><select aria-label={`${mappingNames[role]} element`} value={choices[role]??''} onchange={event=>choices={...choices,[role]:event.currentTarget.value}} disabled={p.active}><option value="">{p.mappings[role]?`Mapped · node ${p.mappings[role]}`:'Choose an element'}</option>{#each controls.filter(c=>(c.visible||(role==='attachment'&&c.file_input))&&!c.disabled) as control(control.id)}<option value={control.id}>{control.id} · {control.label||control.role||control.tag}</option>{/each}</select></td><td><div class="row-actions"><button disabled={p.active||!choices[role]} aria-label={`Save ${mappingNames[role]} mapping`} title="Save this mapping" onclick={()=>record(role)}><Icon name="check" size={13}/></button><button disabled={p.active} aria-label={`Pick ${mappingNames[role]} on page`} title="Pick on website" onclick={()=>app.pick(role)}><Icon name="scan" size={13}/></button></div></td></tr>{/each}</tbody></table><section class="section"><h3 style="margin-bottom:12px">Website with a fixed model</h3><p class="field-hint" style="margin-bottom:12px">Use the website’s visible model label when it does not expose a selector. This is recorded as user supplied, not automatically discovered.</p><form class="inline" onsubmit={event=>{event.preventDefault();void app.perform('connector.manual_model',{provider_id:p.id,label:manual.trim()});}}><input aria-label="Fixed model label" bind:value={manual} placeholder="Visible model name" maxlength="240" style="flex:1;min-width:0" required/><button class="secondary" disabled={p.active||!manual.trim()}>Save label</button></form></section><section class="section" style="border:0"><div class="section-title"><h3>Repair learned mappings</h3><button class="text-button" disabled={p.active} onclick={()=>app.perform('connector.reset',{provider_id:p.id,confirmed:true})}>Reset to automatic</button></div><p>Reset clears user-recorded selectors. Automatic discovery then runs against the current document; no prompt is sent.</p></section></div>
<aside><div class="section-title"><h2>Current evidence</h2><span class="tag">Sanitized</span></div><div class="evidence-box">{#if loading}Reading the current document…{:else if evidence}<pre style="font-size:10px">{JSON.stringify(evidence,null,2)}</pre>{:else}No observation has arrived. Open the website, sign in, and rescan.{/if}</div><div class="note"><Icon name="shield" size={15}/><span>Password fields are counted, never read. Network events retain bounded structure and timing, not cookies or authentication headers.</span></div><section class="section"><div class="section-title"><h3>TNN research boundary</h3><span class="count">GATED</span></div><p>{app.snapshot?.detector.reason||'A production-qualified TNN artifact has not been admitted. Symbolic discovery remains authoritative.'}</p><p style="margin-top:12px">This application does not substitute invented TNN predictions for a missing model. The research integration contract and action validator remain separate from production control.</p></section></aside></div>
{:else}<div class="empty-state"><Icon name="scan" size={29}/><h2>Choose a website to inspect</h2><p>Each profile has its own evidence, semantic mappings, and connector version. Start by opening an AI chat website.</p><button class="secondary" onclick={()=>app.navigate('browser')}>Open browser</button></div>{/if}
</div></section>
