<script lang="ts">
  import {app} from '../lib/state/app.svelte';
  import CodeBlock from '../lib/components/CodeBlock.svelte';
  import Icon from '../lib/components/Icon.svelte';
  let protocol=$state<'chat'|'responses'|'messages'>('chat'); let selected=$state('');
  const model=$derived(selected || app.models.find(m=>m.provider.state==='READY')?.id || 'YOUR_OBSERVED_MODEL_ID');
  const base=$derived(`http://127.0.0.1:${app.snapshot?.api.port ?? 7331}`);
  const path=$derived(protocol==='chat'?'/v1/chat/completions':protocol==='responses'?'/v1/responses':'/v1/messages');
  const payload=$derived(protocol==='responses'?{model,input:'Reply with one short sentence.',stream:true}:{model,messages:[{role:'user',content:'Reply with one short sentence.'}],stream:true,...(protocol==='messages'?{max_tokens:256}:{})});
  const code=$derived(`curl --no-buffer '${base}${path}' \\\n  -H 'Content-Type: application/json' \\\n  -H "Authorization: Bearer $BRIDGE_API_KEY" \\\n  --data-binary @- <<'BRIDGE_JSON'\n${JSON.stringify(payload,null,2)}\nBRIDGE_JSON`);
  const python=$derived(`from openai import OpenAI\nimport os\n\nclient = OpenAI(base_url="${base}/v1", api_key=os.environ["BRIDGE_API_KEY"])\nstream = client.chat.completions.create(\n    model=${JSON.stringify(model)},\n    messages=[{"role": "user", "content": "Hello"}],\n    stream=True,\n)\nfor chunk in stream:\n    if chunk.choices:\n        print(chunk.choices[0].delta.content or "", end="", flush=True)`);
</script>
<section class="screen"><div class="page-heading"><div><div class="eyebrow">CLIENT CONNECTION</div><h1>Harness setup</h1><p>Connect clients that support a custom endpoint, local API key and explicit model ID.</p></div></div>
  <div class="two-columns"><article class="panel padded"><h2>Connection details</h2><label class="field">Base URL<div class="input-action"><input readonly value={`${base}/v1`}/><button class="icon-button" aria-label="Copy base URL" onclick={()=>app.clipboard(`${base}/v1`)}><Icon name="copy"/></button></div></label><label class="field">Model<select bind:value={selected}><option value="">{app.models.length?'First ready model':'No discovered models'}</option>{#each app.models as m (m.id)}<option value={m.id}>{m.id} · {m.provider.state.toLowerCase()}</option>{/each}</select></label><div class="field"><span>API key</span><p>The key is revealed only in Settings. It is never inserted into diagnostics or copied configuration templates.</p><button class="secondary" onclick={()=>app.route='settings'}><Icon name="key" size={16}/>Manage local key</button></div></article>
    <article class="panel padded"><h2>Compatibility boundaries</h2><div class="capability-row"><span>OpenAI Chat Completions</span><span class="source-tag">SUBSET</span></div><div class="capability-row"><span>OpenAI Responses</span><span class="source-tag">SUBSET</span></div><div class="capability-row"><span>Anthropic Messages</span><span class="source-tag">SUBSET</span></div><div class="capability-row"><span>Codex / Claude Code end-to-end</span><span class="source-tag">NOT VERIFIED</span></div><p class="muted">Successful HTTP connectivity does not establish full harness compatibility. See PROTOCOL.md for rejected parameters, emulated roles and tool framing.</p></article></div>
  <div class="section-heading"><h2>Streaming smoke request</h2><div class="segmented">{#each ['chat','responses','messages'] as item}<button class:active={protocol===item} onclick={()=>protocol=item as typeof protocol}>{item==='chat'?'Chat Completions':item==='responses'?'Responses':'Messages'}</button>{/each}</div></div><p class="muted">Set <code>BRIDGE_API_KEY</code> in your terminal first. Do not paste the key into shared logs or source files.</p><CodeBlock {code} label={`POST ${path}`}/>
  {#if protocol==='chat'}<CodeBlock code={python} label="OpenAI Python client — custom endpoint example"/>{/if}
  <div class="notice warning"><Icon name="history"/><p>Use <code>X-Bridge-Session</code> for incremental turns, or return the exact full history. Responses clients can use <code>previous_response_id</code>. Restarted sessions are marked lost rather than silently replayed.</p></div>
</section>
