<script lang="ts">
 import {app} from '../lib/state/app.svelte';import Icon from '../lib/components/Icon.svelte';import ExternalClients from '../lib/components/ExternalClients.svelte';
</script>
<section class="screen"><div class="screen-inner">
<header class="screen-head"><div><div class="breadcrumb">Codemax / Harness</div><h1>Connect a client</h1><p>Choose your harness. Use the connection below once. Every model runs through its website session—not a provider API.</p></div><button class="secondary" onclick={()=>app.navigate('providers')}><Icon name="globe" size={15}/>Manage providers</button></header>
<div class="setup-strip"><span class="setup-step"><Icon name="globe" size={16}/><strong>1</strong> Browse & sign in</span><Icon name="arrow" size={14}/><span class="setup-step"><Icon name="scan" size={16}/><strong>2</strong> Models detected automatically</span><Icon name="arrow" size={14}/><span class="setup-step"><Icon name="terminal" size={16}/><strong>3</strong> Connect your harness</span></div>
{#if !app.exposedModels.length}<div class="note"><Icon name="scan" size={17}/><span>No ready models are exposed yet. Keep browsing; login screens and ordinary websites are never published as providers. Open a model menu normally when its options are hidden.</span></div>{/if}
<ExternalClients/>
<details class="advanced-client"><summary>Advanced · MCP versus model connections</summary><p>MCP connects tools to an assistant. A model-provider connection lets a harness use the website model as its model. Codemax keeps both paths separate; adding an MCP server alone does not replace a harness’s model.</p><p style="margin-top:12px">The registry updates live. A harness that caches or requires an explicit model list may need a refresh, restart, or an updated configuration export. Codemax does not secretly overwrite client configuration files.</p><button class="secondary" style="margin-top:16px" onclick={()=>app.navigate('tools')}>Manage website tools<Icon name="arrow" size={14}/></button></details>
</div></section>
