<script lang="ts">
 import {app} from '../lib/state/app.svelte';import * as bridge from '../lib/api/bridge';import {dateTime,number} from '../lib/format';import Icon from '../lib/components/Icon.svelte';
 let level=$state('all');const events=$derived(app.events.filter(e=>level==='all'||e.level===level));
 async function exportLogs(){const data=await app.perform('logs.export');if(data!==undefined)await app.export('bridge-diagnostics.json',{exported_at:new Date().toISOString(),events:data});}
</script>
<section class="screen"><div class="screen-inner"><header class="screen-head"><div><div class="breadcrumb">Workspace / Diagnostics</div><h1>Activity</h1><p>A bounded, redacted view of what the local gateway is doing.</p></div><div class="button-group"><button class="secondary" disabled={!app.ready} onclick={exportLogs}><Icon name="download" size={14}/>Export diagnostics</button></div></header>
<div class="metric-strip"><div><span class="label">Ready providers</span><strong>{app.detectedProviders.filter(p=>p.state==='READY'&&p.exposed).length}<span class="muted" style="font-size:16px;letter-spacing:0"> / {app.detectedProviders.length}</span></strong><small>Independent browser profiles</small></div><div><span class="label">Available models</span><strong>{app.exposedModels.length}</strong><small>Observed or user supplied</small></div><div><span class="label">Completed requests</span><strong>{number(app.snapshot?.metrics.completed_requests)}</strong><small>During this backend process</small></div><div><span class="label">Failed requests</span><strong>{number(app.snapshot?.metrics.failed_requests)}</strong><small>No silent automatic retries</small></div></div>
<div class="section-title"><h2>Gateway events</h2><span class="tag"><span class="dot" class:online={app.ready}></span>Push updates</span></div><div class="filterbar"><span class="muted" style="font-size:11px">{events.length} retained events</span><span class="spacer"></span><select aria-label="Event severity" bind:value={level}><option value="all">All levels</option><option value="ERROR">Errors</option><option value="WARN">Warnings</option><option value="INFO">Information</option><option value="DEBUG">Debug</option></select><button class="text-button" disabled={!app.events.length} onclick={()=>app.ask('Clear retained diagnostics?','This clears the local diagnostic event list. Export any events you need first.','Clear diagnostics',()=>app.perform('logs.clear'))}><Icon name="trash" size={13}/>Clear</button></div>
{#each events as event(event.id)}<div class="log-row"><span class="faint" title={dateTime(event.time)}>{event.time?new Date(event.time*1000).toLocaleTimeString([], {hour12:false}):'—'}</span><span class={`log-level ${event.level}`}>{event.level}</span><code>{event.kind}</code><span class="log-detail">{event.detail}</span></div>{/each}
{#if !events.length}<div class="empty-state"><Icon name="activity" size={26}/><h2>{app.events.length?'No events at this level':'No retained events'}</h2><p>Gateway and connector events will appear here. Debug-level browser metadata requires an explicit logging setting.</p>{#if app.events.length}<button class="secondary" onclick={()=>level='all'}>Show all levels</button>{:else}<button class="text-button" onclick={()=>app.settingsPage('privacy')}>Logging settings<Icon name="arrow" size={13}/></button>{/if}</div>{/if}
<div class="note"><Icon name="shield" size={15}/><span>No prompts, response bodies, authentication headers, or cookies are written to the diagnostic event ring. Export only diagnostics you intend to share.</span></div>
</div></section>
