<script lang="ts">
 import {app} from '../lib/state/app.svelte';import {initials,number,providerText,modelReady,modelStatus} from '../lib/format';import Icon from '../lib/components/Icon.svelte';
 const filters=$derived(app.modelFilters);
 const visible=$derived(app.models.filter(m=>(filters.provider==='all'||m.provider.id===Number(filters.provider))&&(filters.status==='all'||(filters.status==='READY'?modelReady(m,m.provider):filters.status==='DISABLED'?(!m.enabled||!m.provider.exposed):m.provider.state===filters.status))&&`${m.display_name} ${m.id} ${m.provider.label}`.toLowerCase().includes(filters.query.toLowerCase())).sort((a,b)=>(filters.sort==='provider'?a.provider.label.localeCompare(b.provider.label)||a.display_name.localeCompare(b.display_name):a.display_name.localeCompare(b.display_name))*(filters.descending?-1:1)));
 function order(sort:'provider'|'model'){app.modelFilters={...filters,sort,descending:filters.sort===sort?!filters.descending:false};}
 function clear(){app.modelFilters={query:'',provider:'all',status:'all',sort:'provider',descending:false};}
</script>
<section class="screen"><div class="screen-inner"><header class="screen-head"><div><div class="breadcrumb">Workspace / Registry</div><h1>Models</h1><p>The models your websites expose, with evidence—not assumed specifications.</p></div><button class="secondary" disabled={!app.ready} onclick={()=>app.showPopup('add')}><Icon name="plus" size={15}/>Add website</button></header>
<div class="filterbar"><label class="search-field"><Icon name="search" size={15}/><input bind:value={app.modelFilters.query} aria-label="Search models" placeholder="Find a model or provider…"/></label><span class="spacer"></span><select aria-label="Filter by provider" bind:value={app.modelFilters.provider}><option value="all">All detected providers</option>{#each app.detectedProviders as p}<option value={p.id}>{p.label}</option>{/each}</select><select aria-label="Filter by availability" bind:value={app.modelFilters.status}><option value="all">Any status</option><option value="READY">Ready to use</option><option value="DISABLED">Disabled</option><option value="RATE_LIMITED">Rate limited</option><option value="LOGIN_REQUIRED">Sign in required</option></select></div>
<div class="table-scroll"><table><thead><tr><th aria-sort={filters.sort==='model'?(filters.descending?'descending':'ascending'):'none'}><button onclick={()=>order('model')}>MODEL <Icon name="chevron" size={11}/></button></th><th aria-sort={filters.sort==='provider'?(filters.descending?'descending':'ascending'):'none'}><button onclick={()=>order('provider')}>WEBSITE <Icon name="chevron" size={11}/></button></th><th>REASONING</th><th>CONTEXT</th><th>TOOLS</th><th>STATUS</th><th></th></tr></thead><tbody>{#each visible as model(model.id)}<tr><td><div class="inline"><span class="model-letter">{initials(model.display_name).slice(0,2)}</span><div><span class="primary-line">{model.display_name}{#if app.preferences.default_model===model.id}<span class="count">DEFAULT</span>{/if}</span><span class="secondary-line mono">{model.id}</span></div></div></td><td><button class="text-button" style="padding:0;font-size:12px" onclick={()=>app.openProvider(model.provider.id)}>{model.provider.label}</button></td><td><span>{model.reasoning?.control_observed?'Control found':'Unknown'}</span><span class="secondary-line">{model.reasoning?.control_observed?'Observed on website':'Not asserted'}</span></td><td>{model.provider.context_hint?number(model.provider.context_hint):model.context.nominal?number(model.context.nominal):model.context.advertised_label||'Unknown'}<span class="secondary-line">{model.provider.context_hint?'User supplied':model.context.nominal?'Provider reported':model.context.advertised_label?'Website label · exact count unknown':'No limit exposed'}</span></td><td>Text bridge<span class="secondary-line">{model.vision===true?'Vision observed':'Vision unknown'}</span></td><td><span class="tag" class:ready={modelReady(model,model.provider)} class:attention={model.provider.state==='RATE_LIMITED'}><span class="dot" class:online={modelReady(model,model.provider)} class:warn={model.provider.state==='RATE_LIMITED'}></span>{modelStatus(model,model.provider)}</span></td><td><div class="row-actions"><button class="icon-button" title="Copy model ID" aria-label={`Copy ${model.display_name} model ID`} onclick={()=>app.clipboard(model.id)}><Icon name="copy" size={14}/></button><button title="Use as the codemax/default model" aria-label={`Set ${model.display_name} as default`} disabled={!app.ready||!modelReady(model,model.provider)||app.preferences.default_model===model.id||app.busy('settings.update')} onclick={()=>app.settings({default_model:model.id})}><Icon name="check" size={14}/></button></div></td></tr>{/each}</tbody></table></div>
{#if !visible.length}<div class="empty-state"><Icon name="layers" size={28}/><h2>{app.models.length?'No models match those filters':'Your models will appear here'}</h2><p>{app.models.length?'Try another website or search term.':'Open a provider, sign in, and open its model menu. Discovery will update this registry as controls become visible.'}</p>{#if app.models.length}<button class="secondary" onclick={clear}>Clear filters</button>{:else}<button class="secondary" onclick={()=>app.newTab()}>Open browser<Icon name="arrow" size={14}/></button>{/if}</div>{/if}
<div class="table-foot"><span>{visible.length} of {app.models.length} models · Updates from the Zag registry</span><span>Unknown values are never filled with guesses.</span></div>
<div class="note"><Icon name="shield" size={16}/><span>Names and capabilities come from website evidence. Unknown limits stay unknown; estimates are never exact token counts.</span></div>
</div></section>
