<script lang="ts">
 import {app} from '../lib/state/app.svelte';import Icon from '../lib/components/Icon.svelte';import {number,providerText,initials} from '../lib/format';
 let selected=$state<number|null>(null),hint=$state(0),reasoning=$state(''),label=$state('');let loaded=0;
 const sites=$derived(app.detectedProviders);
 const current=$derived(sites.find(p=>p.id===selected)||sites.find(p=>p.id===app.selectedProvider)||sites[0]);
 const ordinary=$derived(app.providers.filter(p=>!p.detected||p.dismissed));
 $effect(()=>{if(current&&loaded!==current.id){loaded=current.id;label=current.label;hint=current.context_hint;reasoning=current.reasoning_value;}});
 async function policy(patch:Record<string,unknown>){if(current)await app.perform('provider.update',{provider_id:current.id,...patch});}
 async function save(){await policy({label,context_hint:Number(hint),reasoning_value:reasoning});}
</script>
<section class="screen"><div class="screen-inner">
 <header class="screen-head"><div><div class="breadcrumb">Codemax / Discovered websites</div><h1>Providers</h1><p>Only websites with positive chat and model evidence appear here. Choose what your harness can use.</p></div><button class="secondary" onclick={()=>app.newTab()}><Icon name="plus" size={15}/>Browse a website</button></header>
 {#if current}
 <div class="provider-settings"><nav class="provider-selector" aria-label="Detected providers">
 {#each sites as site(site.id)}<button class="provider-choice" class:active={current.id===site.id} onclick={()=>selected=site.id}><span class="site-letter">{initials(site.label)}</span><span class="site-details"><strong>{site.label}</strong><small>{site.models.filter(m=>m.enabled).length} enabled · {providerText(site)}</small></span></button>{/each}
 <p class="discovery-note"><Icon name="scan" size={13}/> Discovery runs while you browse. It never opens menus, changes your model, or spends quota just to test a website.</p></nav>
 <div>
 <section class="section"><div class="section-title"><div><h2>{current.label}</h2><p class="mono" style="font-size:11px;margin-top:7px">{current.origin}</p></div><button class="secondary" onclick={()=>app.openProvider(current.id)}><Icon name="globe" size={14}/>Open tab</button></div>
 <label class="setting-line"><div><strong>Available to my harness</strong><p>Publish enabled models to the local model registry. Turning this off also cancels an active request.</p></div><input type="checkbox" aria-label="Expose provider to harness" checked={current.exposed} onchange={e=>policy({exposed:e.currentTarget.checked})}/></label>
 <label class="setting-line"><div><strong>Keep discovering this website</strong><p>Watch control changes and selected capability fields. Passwords and authentication data stay in the browser.</p></div><input type="checkbox" aria-label="Scan provider automatically" checked={current.scan_enabled} onchange={e=>policy({scan_enabled:e.currentTarget.checked})}/></label>
 <div class="discovery-note"><Icon name="check" size={14}/> {current.discovery_reason}<br/><span class="faint">Website evidence, not a guarantee of the model’s underlying identity.</span></div></section>
 <section class="section"><div class="section-title"><h2>Exposed models</h2><span class="tag">{current.models.filter(m=>m.enabled).length} of {current.models.length}</span></div>
 {#each current.models as model(model.id)}<label class="setting-line"><div><strong>{model.display_name}</strong><p><code>{model.id}</code> · {model.available?'Observed in this browser session':'Recheck when this website opens'}</p></div><input type="checkbox" aria-label={`Expose ${model.display_name}`} checked={model.enabled} onchange={e=>app.perform('model.update',{provider_id:current.id,model:model.id,enabled:e.currentTarget.checked})}/></label>{/each}
 </section>
 <section class="section"><div class="section-title"><h2>What the website exposes</h2><span class="tag">Evidence, not guesses</span></div><table class="permission-table"><tbody><tr><td>Current model</td><td>{current.current_model||'Not exposed yet'}</td></tr><tr><td>Reasoning levels</td><td>{current.reasoning_modes?.length?current.reasoning_modes.map(m=>m.label).join(' · '):current.mappings.reasoning?'Control observed; options unknown':'Unknown'}</td></tr>{#each current.models as model(model.id)}<tr><td>{model.display_name} · context</td><td>{model.context.nominal?`${number(model.context.nominal)} · website reported`:'Unknown'}</td></tr><tr><td>{model.display_name} · tokenizer</td><td>{model.tokenizer.name?`${model.tokenizer.name} · identity only`:'Unknown; usage remains estimated'}</td></tr>{/each}</tbody></table><p class="field-hint" style="margin-top:14px">A model’s nominal context window does not establish the website’s usable conversation budget. Hidden options become discoverable when you open their controls normally.</p></section>
 <details class="advanced-client"><summary>Advanced · overrides, mapping, and lifecycle</summary>
 <label class="field"><span>Display name</span><input bind:value={label} maxlength="240"/></label>
 <label class="field"><span>Context budget override · explicitly user supplied</span><input type="number" bind:value={hint} min="0" max="10000000"/><span class="field-hint">0 leaves the limit unknown. This does not change provider limits or prove exact token counts.</span></label>
 <label class="field"><span>Preferred reasoning value</span><select bind:value={reasoning}><option value="">Leave website default</option>{#each current.reasoning_modes||[] as mode}<option value={mode.value}>{mode.label}</option>{/each}</select></label>
 <div class="button-group"><button class="primary" disabled={!!current.active} onclick={save}>Save overrides</button><button class="secondary" onclick={()=>{app.selectedProvider=current.id;app.navigate('detector');}}>Inspect mappings</button><button class="secondary" onclick={()=>app.perform('provider.rescan',{provider_id:current.id})}>Rescan</button></div>
 <label class="setting-line"><div><strong>Keep this website awake</strong><p>Avoid idle suspension. Active requests are always kept awake.</p></div><input type="checkbox" checked={current.pinned} onchange={e=>policy({pinned:e.currentTarget.checked})}/></label>
 <button class="text-button danger-text" style="margin-top:18px" onclick={()=>policy({dismissed:true,exposed:false})}>Treat as an ordinary website</button>
 </details></div></div>
 {:else}<div class="empty-state"><Icon name="globe" size={28}/><h2>Browse first. Providers follow.</h2><p>No websites have passed discovery yet. Open an AI chat website and sign in normally. A search box, login form, model mention, or ordinary page does not make a provider.</p><button class="primary" onclick={()=>app.newTab()}>Open a browser tab<Icon name="arrow" size={14}/></button></div>{/if}
 {#if ordinary.length}<details class="advanced-client"><summary>Other browser profiles · {ordinary.length} not exposed</summary>{#each ordinary as site(site.id)}<div class="setting-line"><div><strong>{site.label}</strong><p>{site.dismissed?'Excluded from discovery':site.discovery_reason||'No positive provider evidence'} · {site.origin}</p></div><button class="text-button" onclick={()=>app.openProvider(site.id)}>Open</button>{#if site.dismissed}<button class="text-button" onclick={()=>app.perform('provider.update',{provider_id:site.id,dismissed:false,scan_enabled:true})}>Resume discovery</button>{/if}</div>{/each}</details>{/if}
</div></section>
