<script lang="ts">
 import {app} from '../lib/state/app.svelte';import {stateText,dateTime,number} from '../lib/format';import Icon from '../lib/components/Icon.svelte';
 let query=$state(''),status=$state('all');
 const visible=$derived([...app.sessions].filter(s=>(status==='all'||s.status===status)&&`${s.title} ${s.id} ${s.model}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.last_used-a.last_used));
 async function rename(event:Event,id:string){const value=(event.currentTarget as HTMLInputElement).value.trim();const s=app.sessions.find(s=>s.id===id);if(s&&value!==s.title)await app.perform('session.rename',{session_id:id,title:value});}
</script>
<section class="screen"><div class="screen-inner"><header class="screen-head"><div><div class="breadcrumb">Workspace / Continuity</div><h1>Sessions</h1><p>Client conversations mapped to their website chats. Resume without replaying the whole conversation.</p></div><span class="tag"><span class="dot" class:busy={app.sessions.some(s=>s.status==='ACTIVE')}></span>{app.sessions.filter(s=>s.status==='ACTIVE').length} running</span></header>
<div class="filterbar"><label class="search-field"><Icon name="search" size={15}/><input aria-label="Search sessions" bind:value={query} placeholder="Search session, title, or model…"/></label><span class="spacer"></span><select aria-label="Filter session status" bind:value={status}><option value="all">All sessions</option><option value="ACTIVE">Running</option><option value="IDLE">Idle</option><option value="PROVIDER_LOST">Reconnect</option><option value="EXPIRED">Ended</option></select></div>
<div class="table-scroll"><table><thead><tr><th>CONVERSATION</th><th>MODEL / WEBSITE</th><th>TURNS</th><th>CONTEXT ESTIMATE</th><th>STATUS</th><th></th></tr></thead><tbody>{#each visible as s(s.id)}{@const provider=app.providers.find(p=>p.id===s.provider)}<tr><td style="min-width:190px"><input class="session-title-input" aria-label={`Title for session ${s.id}`} value={s.title} placeholder="Untitled conversation" maxlength="240" onchange={event=>rename(event,s.id)}/><button class="text-button" style="padding:0;min-height:18px;display:block" title="Copy session ID" onclick={()=>app.clipboard(s.id)}><span class="secondary-line mono">{s.id}</span></button><span class="secondary-line">{dateTime(s.last_used)}</span></td><td>{s.model.split('/').at(-1)}<span class="secondary-line">{provider?.label??'Website removed'}</span></td><td class="mono">{s.turn_count}</td><td>{number(s.context.estimated_used)}<span class="secondary-line">Conservative byte bound</span></td><td><span class="tag" class:ready={s.status==='ACTIVE'||s.status==='IDLE'} class:attention={['PROVIDER_LOST','RATE_LIMITED'].includes(s.status)}><span class="dot" class:busy={s.status==='ACTIVE'} class:online={s.status==='IDLE'}></span>{stateText(s.status)}</span></td><td><div class="row-actions">{#if s.status==='ACTIVE'}<button class="secondary" onclick={()=>app.cancel(s.id)}><Icon name="stop" size={12}/>Stop</button>{:else if s.status==='PROVIDER_LOST'}<button class="secondary" disabled={!s.url||!provider} onclick={()=>app.resume(s.id)}><Icon name="refresh" size={12}/>Resume</button>{:else if s.status!=='EXPIRED'}<button class="text-button" disabled={!provider} onclick={()=>app.openProvider(s.provider)}><Icon name="globe" size={13}/>Open</button>{/if}{#if s.status!=='EXPIRED'}<button class="icon-button" title="End this local session" aria-label={`End session ${s.id}`} onclick={()=>app.perform('session.end',{session_id:s.id})}><Icon name="close" size={13}/></button>{/if}</div></td></tr>{/each}</tbody></table></div>
{#if !visible.length}<div class="empty-state"><Icon name="history" size={29}/><h2>{app.sessions.length?'No matching conversations':'No conversations yet'}</h2><p>Connect a client to the local API. Its session will appear here when it sends the first request.</p><button class="secondary" onclick={()=>app.navigate('harness')}>Connect a client<Icon name="arrow" size={14}/></button></div>{/if}
<div class="table-foot"><span>{visible.length} conversations</span><span>Session metadata and digests persist; prompt bodies do not.</span></div><div class="note"><Icon name="shield" size={16}/><span>Restoration uses the website conversation URL and message-digest receipts. A missing or changed conversation is rejected rather than silently starting over. The context figure is an upper-bound estimate, not an exact tokenizer count.</span></div>
</div></section>
