<script lang="ts">
  import {onDestroy} from 'svelte';
  import {app} from '../lib/state/app.svelte';
  import * as bridge from '../lib/api/bridge';
  import Icon from '../lib/components/Icon.svelte';
  let key=$state(''); let port=$state(app.snapshot?.api.desired_port??7331); let timer: ReturnType<typeof setTimeout>|undefined;
  async function reveal() {const result=await app.perform<{token:string}>('key.reveal');if(result){key=result.token;clearTimeout(timer);timer=setTimeout(()=>key='',15000);}}
  onDestroy(()=>{clearTimeout(timer);key='';});
  async function restart() {try {await bridge.restart();}catch(error){app.error=String(error);}}
</script>
<section class="screen settings-screen"><div class="page-heading"><div><div class="eyebrow">LOCAL CONTROL</div><h1>Settings</h1><p>Access, storage and process lifecycle. Sensitive defaults cannot be enabled accidentally.</p></div></div>
  <article class="panel padded"><div class="section-heading"><h2>Local API</h2><span class="subtle-tag">Loopback only</span></div><div class="settings-row"><div><h3>Listening port</h3><p>Changes apply after restarting the Zag sidecar. Current sessions will lose continuity.</p></div><div class="inline-form"><input type="number" min="1024" max="65535" bind:value={port} aria-label="Local API port"/><button class="secondary" disabled={!app.ready||!Number.isInteger(port)||port<1024||port>65535} onclick={()=>app.perform('settings.update',{port})}>Save port</button></div></div>
    <div class="settings-row"><div><h3>Local API key</h3><p>Shown for 15 seconds. Copying places the key on your system clipboard.</p></div><div class="button-group"><button class="secondary" disabled={!app.ready} onclick={reveal}><Icon name="key" size={16}/>Reveal</button><button class="secondary" disabled={!key} onclick={()=>app.clipboard(key)}><Icon name="copy" size={16}/>Copy key</button><button class="text-button danger-text" disabled={!app.ready} onclick={()=>{key=''; void app.showPopup('rotate-key');}}>Regenerate</button></div></div>
    {#if key}<div class="secret-field"><code>{key}</code><button class="text-button" onclick={()=>key=''}>Hide now</button></div>{/if}
    <div class="settings-row"><div><h3>Restart backend</h3><p>Old requests are never replayed. A handshake is required before the host becomes ready.</p></div><button class="secondary" disabled={!bridge.native()} onclick={restart}><Icon name="refresh" size={16}/>Restart Zag</button></div>
  </article>
  <article class="panel padded"><h2>Privacy and safety</h2><div class="settings-row"><div><h3>Raw browser capture</h3><p>Passwords, cookies, request headers and response payload capture are excluded.</p></div><span class="source-tag">DISABLED</span></div><div class="settings-row"><div><h3>Automatic provider fallback</h3><p>Quota and login errors stop the request rather than rotating identities or accounts.</p></div><span class="source-tag">DISABLED</span></div><div class="settings-row"><div><h3>Session persistence</h3><p>Gateway metadata only. Provider login state stays in its isolated browser profile.</p></div><span class="subtle-tag">Minimal</span></div><div class="settings-row"><div><h3>Clear selected browser profile</h3><p>Deletes local cookies and website storage for {app.provider?.label??'the selected provider'}. Does not delete remote account data.</p></div><button class="secondary danger-text" disabled={!app.provider||!app.ready} onclick={()=>app.showPopup('clear-profile')}>Clear profile</button></div></article>
  <article class="panel padded"><h2>Interface</h2><div class="settings-row"><div><h3>Density</h3><p>Applies to tables and navigation. Motion follows your system preference.</p></div><select bind:value={app.density} aria-label="Interface density"><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></div><div class="settings-row"><div><h3>Build qualification</h3><p>Linux x86_64 source alpha. See the packaged execution report for tests actually run.</p></div><span class="source-tag">NOT RELEASE QUALIFIED</span></div></article>
</section>
