<script lang="ts">
 import {tick} from 'svelte';import {app} from '../lib/state/app.svelte';import * as bridge from '../lib/api/bridge';
 import ToolLibrary from '../lib/components/tools/ToolLibrary.svelte';import Icon from '../lib/components/Icon.svelte';import {errorText} from '../lib/format';import type {McpServer} from '../lib/types/bridge';
 const draft=$derived(app.toolDraft);let forRun=$state(false),formError=$state('');
 let library=$state(false),toolFilter=$state('');
 let consent=$state<McpServer|null>(null),trust=$state(false),consentPanel=$state<HTMLElement>();
 let imported=$state<Array<{label:string;command:string;args:string[]}>>([]),importChoice=$state(0);
 const servers=$derived(app.snapshot?.mcp_servers??[]),run=$derived(app.snapshot?.mcp_run);
 const running=$derived(!!app.activeTask);
 const model=$derived(draft.chosen?app.exposedModels.find(m=>m.id===draft.chosen):app.exposedModels.find(m=>m.provider.id===app.selectedProvider)||app.exposedModels[0]);
 const tools=$derived(servers.flatMap(server=>server.tools.map(tool=>({...tool,server}))));
 const enabled=$derived(tools.filter(t=>t.enabled&&t.server.state==='READY'));
 const pending=$derived(tools.find(t=>t.alias===run?.tool));
 const blocker=$derived(!app.ready?'Reconnect the local gateway to start tasks.':!model?'Open a website and select an available model.':!enabled.length?'Connect a tool server and enable at least one tool below.':!draft.task.trim()?'Describe what the model should do.':!Number.isInteger(draft.turnBudget)||draft.turnBudget<10||draft.turnBudget>500||!Number.isInteger(draft.workMinutes)||draft.workMinutes<5||draft.workMinutes>240?'Choose 10–500 turns and 5–240 active minutes.':'');
 let lastApproval='';
 $effect(()=>{
  const key=run?.state==='PERMISSION_REQUIRED'?`${run.id}:${run.call_id}:${run.tool}:${run.arguments}`:'';
  if(lastApproval!==key){lastApproval=key;forRun=false;}
 });
 $effect(()=>{if(consent)void tick().then(()=>{consentPanel?.scrollIntoView({block:'nearest'});consentPanel?.focus();});});
 async function add(){
  formError='';
  try{const args=JSON.parse(draft.argv);if(!Array.isArray(args)||args.some(a=>typeof a!=='string'))throw Error('Arguments must be a JSON array of strings, for example ["--config", "file.json"].');
   const result=await app.perform<{server_id:number}>('mcp.server.add',{label:draft.label.trim(),command:draft.command.trim(),args});
   if(result){draft.adding=false;draft.label='';draft.command='';draft.argv='[]';app.notification='Server saved. Review and allow the local process before connecting.';}
  }catch(error){formError=error instanceof SyntaxError?'Arguments are not valid JSON. Use a list of quoted strings, for example ["--help"].':errorText(String(error));}
 }
 async function importServers(){
  try{const file=await bridge.importDocument();if(!file)return;const source=(file.mcpServers??file) as Record<string,unknown>;
   imported=Object.entries(source).flatMap(([name,v])=>{const x=v as {command?:unknown;args?:unknown};return x&&typeof x.command==='string'&&Array.isArray(x.args)&&x.args.every(a=>typeof a==='string')?[{label:name,command:x.command,args:x.args as string[]}]:[];});
   if(!imported.length)throw Error('No supported local server definitions were found. Remote URLs and credentials are not imported.');
   importChoice=0;useImported();draft.adding=true;formError='';
  }catch(error){app.error=String(error);}
 }
 function useImported(){const item=imported[importChoice];if(item){draft.label=item.label;draft.command=item.command;draft.argv=JSON.stringify(item.args,null,2);}}
 async function connect(){if(!consent||!trust)return;const result=await app.perform('mcp.server.connect',{server_id:consent.id,confirmed:true});if(result!==undefined){consent=null;trust=false;}}
 async function start(){if(!model||blocker)return;forRun=false;await app.perform('mcp.run.start',{provider_id:model.provider.id,model:model.id,task:draft.task,auto_continue:draft.automatic,turn_budget:draft.turnBudget,work_minutes:draft.workMinutes});}
 async function approve(){if(run&&!app.busy('mcp.run.approve'))await app.perform('mcp.run.approve',{run_id:run.id,call_id:run.call_id,confirmed:true,allow_run:forRun});}
 async function cancel(){if(run)await app.perform('mcp.run.cancel',{run_id:run.id});}
 function remove(server:McpServer){void app.ask(`Remove ${server.label}?`,'Disconnect this local server and remove its saved definition. The executable and its files will not be deleted.','Remove server',()=>app.perform('mcp.server.remove',{server_id:server.id,confirmed:true}));}
 function chooseRecipe(value:{label:string;command:string;args:string[]}){draft.label=value.label;draft.command=value.command;draft.argv=JSON.stringify(value.args,null,2);draft.adding=true;library=false;formError='';}
 const runLabels:Record<string,string>={PAUSED:'Ready to continue',IDLE:'Idle',GENERATING:'Model is responding',PERMISSION_REQUIRED:'Waiting for your approval',EXECUTING_TOOL:'Running the approved tool',RESULT_READY:'Result ready to send',COMPLETED:'Completed',FAILED:'Task failed',CANCELLED:'Stopped'};
</script>
<section class="screen"><div class="screen-inner tools-screen">
 <header class="screen-head"><div><div class="breadcrumb">Codemax / Website tasks</div><h1>Website tasks</h1><p>Choose a task and its tools. Approve access, then let the same conversation continue.</p></div><div class="button-group">{#if !running}<button class="secondary" aria-expanded={library} disabled={!app.ready} onclick={()=>{library=!library;draft.adding=false;}}>Tool library</button><details class="setup-menu"><summary>More setup</summary><div><button class="secondary" disabled={running||!app.ready} onclick={importServers}>Import configuration</button><button class="secondary" disabled={running||!app.ready} aria-expanded={draft.adding} onclick={()=>draft.adding=!draft.adding}><Icon name="plus" size={15}/>Add tool server</button></div></details>{/if}</div></header>
 {#if run&&run.state!=='IDLE'}<section class="section task-activity" aria-label="MCP task activity"><div class="section-title"><h2>Task activity</h2><span class="tag" class:attention={run.state==='PERMISSION_REQUIRED'}>{runLabels[run.state]} · {run.turns} {run.turns===1?'turn':'turns'} · {run.calls} {run.calls===1?'call':'calls'}</span></div>
 {#if run.error&&!['CANCELLED','PAUSED'].includes(run.state)}<p class="error-banner" role="alert">{errorText(run.error)}</p>{/if}
 {#if run.state==='PAUSED'}<div class="task-pause"><p>Reached the chosen work budget at a safe boundary. Your conversation, pending call and last result are retained. No completed tool is replayed.</p><button class="primary" disabled={!app.ready||!run.can_resume||app.busy('mcp.run.resume')} onclick={()=>app.perform('mcp.run.resume',{run_id:run.id})}>{app.busy('mcp.run.resume')?'Continuing…':'Continue task'}</button><p class="field-hint">Continuing renews the work budget, not tool permissions. Broader grants must be approved again. Progress is retained in this app session, not after a restart.</p></div>{/if}
 {#if run.state==='GENERATING'||run.state==='EXECUTING_TOOL'}<div class="task-running" role="status"><span class="mini-working" aria-hidden="true"></span><span>{run.state==='EXECUTING_TOOL'?(pending?.server.progress_message||'Waiting for the approved tool to finish…'):'Waiting for the website model…'}</span></div>{/if}
 {#if run.state==='PERMISSION_REQUIRED'}<div class="tool-call"><div class="section-title"><h3>Approve this tool call</h3><Icon name="shield" size={17}/></div><p><strong>{pending?.name||run.tool}</strong> · {pending?.server.label||'Server unavailable'}</p><pre class="code">{run.arguments}</pre><p class="field-hint">The result will be sent to {app.providers.find(p=>p.id===run.provider_id)?.label||'the selected website'}. Check paths, commands and destinations before approving.</p>
 <details class="advanced-client"><summary>Advanced · automatic execution for this task</summary><label class="setting-line"><div><strong>Allow this tool for the rest of this task</strong><p>Includes future calls with different arguments. This is not a path-limited file permission. The grant ends at the next work-budget pause, after 30 minutes, when the task ends, or when the connection changes.</p></div><input type="checkbox" aria-label="Allow MCP tool for task" bind:checked={forRun} disabled={!app.ready||app.busy('mcp.run.approve')}/></label></details>
 <div class="button-group"><button class="primary" disabled={!app.ready||!pending||app.busy('mcp.run.approve')} onclick={approve}>{app.busy('mcp.run.approve')?'Approving…':forRun?'Allow tool for this task':'Allow once'}</button><button class="secondary" disabled={!app.ready||app.busy('mcp.run.cancel')} onclick={cancel}>Deny and stop</button></div></div>{/if}
 {#if run.state==='RESULT_READY'}<p>The approved tool finished. Send its result to continue the website conversation.</p><button class="primary" disabled={!app.ready||app.busy('mcp.run.continue')} onclick={()=>app.perform('mcp.run.continue',{run_id:run.id})}>Insert result and send</button>{/if}
 {#if run.answer}<pre class="tool-answer">{run.answer}</pre>{/if}
 {#if run.last_result}<details class="advanced-client"><summary>Last tool result · untrusted data</summary><pre class="code">{run.last_result}</pre></details>{/if}
 {#if running}<div class="button-group" style="margin-top:15px"><button class="secondary danger-text" disabled={!app.ready||app.busy('mcp.run.cancel')} onclick={cancel}>Stop task and revoke permissions</button><button class="text-button" disabled={!app.ready} onclick={()=>app.openProvider(run.provider_id)}>Show website</button></div>{/if}
 </section>{/if}
 {#if !running&&!library&&!draft.adding&&!consent}<section class="section"><div class="section-title"><h2>Start a task</h2><span class="tag">{enabled.length} enabled {enabled.length===1?'tool':'tools'}</span></div>
 <label class="field"><span>Website model</span><select aria-label="MCP website model" value={draft.chosen||model?.id||''} onchange={e=>draft.chosen=e.currentTarget.value} disabled={!app.ready||!app.exposedModels.length}>{#if !model}<option value="">Select an available model</option>{/if}{#each app.exposedModels as item(item.id)}<option value={item.id}>{item.display_name} · {item.provider.label}</option>{/each}</select></label>
 <label class="field"><span>What should the model do?</span><textarea aria-label="MCP task" bind:value={draft.task} maxlength="8191" rows="3" placeholder="Describe a task for the selected website model"></textarea><span class="field-hint">Your task, enabled tool descriptions and approved results are shared with the selected website. Drafts stay in memory until you close the application.</span></label>
 <details class="advanced-client task-options"><summary>Task options</summary><label class="setting-line"><div><strong>Automatically continue after approved tools</strong><p>Insert results and send the next turn. Tool execution still requires your approval.</p></div><input type="checkbox" aria-label="Automatically continue tool results" bind:checked={draft.automatic}/></label>
 <div class="budget-fields"><label class="field"><span>Model turns per work budget</span><input type="number" aria-label="Task turn budget" min="10" max="500" step="1" bind:value={draft.turnBudget}/></label><label class="field"><span>Active minutes per work budget</span><input type="number" aria-label="Task work minutes" min="5" max="240" step="1" bind:value={draft.workMinutes}/></label></div>
 <p class="field-hint">Waiting for your approval does not spend the work budget. A running tool is not interrupted when the budget ends; the task pauses at its next safe boundary. Site quotas, context limits and stalled connections still apply.</p></details>
 <div class="button-group"><button class="primary" disabled={!!blocker||app.busy('mcp.run.start')} onclick={start}><Icon name="arrow" size={15}/>{app.busy('mcp.run.start')?'Starting…':'Start in website'}</button>{#if model}<button class="text-button" disabled={!app.ready} onclick={()=>app.openProvider(model.provider.id)}>Show website</button>{/if}</div>
 <p class="field-hint" role="status" style="margin-top:12px">{blocker||'Approved results continue automatically unless disabled in Task options. No provider API key is required.'}</p>
 </section>{/if}
 {#if library&&!running}<section class="section"><div class="section-title"><h2>Tool library</h2><button class="text-button" onclick={()=>library=false}>Close library</button></div><ToolLibrary onchoose={chooseRecipe} disabled={!app.ready}/></section>{/if}
 {#if draft.adding&&!running}<section class="section" aria-label="MCP server editor"><h2>Add an MCP server</h2><form onsubmit={e=>{e.preventDefault();void add();}}>
 {#if imported.length}<label class="field"><span>Imported definition</span><select bind:value={importChoice} onchange={useImported}>{#each imported as definition,i}<option value={i}>{definition.label}</option>{/each}</select><span class="field-hint">Command and arguments only. No credentials or environment values are copied.</span></label>{/if}
 <label class="field"><span>Name</span><input aria-label="MCP server name" bind:value={draft.label} maxlength="120" required/></label>
 <label class="field"><span>Executable</span><input class="mono" aria-label="MCP executable" bind:value={draft.command} maxlength="2000" required/><span class="field-hint">An installed command or absolute executable path. Arguments go below; do not paste a shell command.</span></label>
 <label class="field"><span>Arguments · JSON array</span><textarea class="mono" aria-label="MCP arguments" rows="3" bind:value={draft.argv}></textarea></label>
 {#if formError}<p class="form-error" role="alert">{formError}</p>{/if}
 <div class="button-group"><button class="primary" disabled={!app.ready||!draft.label.trim()||!draft.command.trim()||app.busy('mcp.server.add')}>{app.busy('mcp.server.add')?'Saving…':'Save server'}</button><button type="button" class="secondary" onclick={()=>draft.adding=false}>Cancel</button></div></form></section>{/if}
 {#if consent}<section bind:this={consentPanel} tabindex="-1" class="section permission-box" aria-label="Local process permission"><div class="section-title"><h2>Allow this local process?</h2><Icon name="shield" size={18}/></div><p><strong>{consent.label}</strong> runs with your computer user account’s access. A package runner may download code. Tool approval does not sandbox the server itself.</p><pre class="code">{consent.command}{'\n'}{JSON.stringify(consent.args,null,2)}</pre><label class="setting-line"><span>I trust this executable and its arguments.</span><input type="checkbox" aria-label="Trust MCP executable" bind:checked={trust}/></label><div class="button-group"><button class="primary" disabled={!app.ready||!trust||app.busy('mcp.server.connect')} onclick={connect}>{app.busy('mcp.server.connect')?'Connecting…':'Allow process and connect'}</button><button class="secondary" onclick={()=>{consent=null;trust=false;}}>Do not run</button></div></section>{/if}
 {#if !running&&!library&&!draft.adding&&!consent}<section class="section"><div class="section-title"><h2>Tool servers</h2><span class="tag">{servers.length} configured</span></div>
 {#if !servers.length}<div class="discovery-note"><Icon name="terminal" size={16}/><div>No tool servers configured. Import an existing MCP configuration or add a trusted executable. Your coding client’s model connection does not require an MCP server.</div></div>{/if}
 {#each servers as server(server.id)}<div class="tool-server"><div class="section-title"><div><strong>{server.label}</strong><p class="field-hint">{server.state.toLowerCase().replaceAll('_',' ')} · {server.tools.filter(t=>t.enabled).length} {server.tools.filter(t=>t.enabled).length===1?'tool':'tools'} enabled</p></div><div class="button-group">{#if ['DISCONNECTED','ERROR'].includes(server.state)}<button class="secondary" disabled={running||!app.ready} onclick={()=>{consent=server;trust=false;}}>Connect</button>{:else}<button class="secondary" disabled={running||!app.ready||app.busy('mcp.server.connect')} onclick={()=>app.perform('mcp.server.disconnect',{server_id:server.id})}>Disconnect</button>{/if}</div></div>
 {#if server.error}<p class="error-banner" role="alert">{errorText(server.error)}</p>{/if}
 {#if server.tools.length}<details class="advanced-client tool-catalog"><summary>Choose tools · {server.tools.filter(t=>t.enabled).length} of {server.tools.length} enabled</summary><label class="field"><span>Find a tool</span><input type="search" aria-label={`Filter ${server.label} tools`} bind:value={toolFilter}/></label>
 {#each server.tools.filter(t=>`${t.name} ${t.description}`.toLowerCase().includes(toolFilter.toLowerCase())) as tool(tool.alias)}<label class="setting-line"><div><strong>{tool.name}</strong><p>{tool.description}</p></div><input type="checkbox" aria-label={`Enable MCP tool ${tool.name}`} checked={tool.enabled} disabled={running||!app.ready||server.state!=='READY'} onchange={e=>{const value=e.currentTarget.checked;e.currentTarget.checked=tool.enabled;void app.perform('mcp.tool.update',{tool:tool.alias,enabled:value});}}/></label>{/each}{#if !server.tools.some(t=>`${t.name} ${t.description}`.toLowerCase().includes(toolFilter.toLowerCase()))}<p class="field-hint">No tools match. <button class="text-button" onclick={()=>toolFilter=''}>Clear filter</button></p>{/if}<p class="field-hint">Up to 32 enabled tools within the shared schema budget. Descriptions are sent to the website when a task starts.</p></details>{/if}
 <details class="advanced-client"><summary>Advanced · executable and tool schemas</summary><p class="field-hint">MCP {server.protocol||'not negotiated'} · local stdio</p><pre class="code">{server.command}{'\n'}{JSON.stringify(server.args,null,2)}</pre>{#each server.tools as tool(tool.alias)}<details><summary>{tool.name}</summary><pre class="code">{JSON.stringify(tool.schema,null,2)}</pre></details>{/each}<p class="field-hint">Descriptions are supplied by the server, not a security guarantee. Reconnecting or a changed catalog resets enabled choices and task grants.</p><button class="text-button danger-text" disabled={running||!app.ready} onclick={()=>remove(server)}>Remove server</button></details></div>{/each}
 </section>
{/if}
</div></section>
