<script lang="ts">
 import {onDestroy} from 'svelte';import {app} from '../state/app.svelte';import * as bridge from '../api/bridge';import Icon from '../components/Icon.svelte';
 type Client='opencode'|'claude'|'chat'|'responses'|'messages';let client=$state<Client>('opencode'),selected=$state(''),probing=$state(false),probeMessage=$state('');let timer:ReturnType<typeof setTimeout>;
 const endpoint=$derived(`http://127.0.0.1:${app.snapshot?.api.port??7331}`);
 const model=$derived(selected||app.preferences.default_model||app.models[0]?.id||'bridge/default');
 const clients:Array<{id:Client;name:string}>=[{id:'opencode',name:'OpenCode'},{id:'claude',name:'Claude Code'},{id:'chat',name:'Chat API'},{id:'responses',name:'Responses API'},{id:'messages',name:'Messages API'}];
 const config=$derived({$schema:'https://opencode.ai/config.json',model:`bridge/${model}`,provider:{bridge:{npm:'@ai-sdk/openai-compatible',name:'Desktop AI Bridge',options:{baseURL:`${endpoint}/v1`,apiKey:'{env:BRIDGE_API_KEY}'},models:Object.fromEntries(app.models.map(m=>[m.id,{name:`${m.provider.label} / ${m.display_name}`}]))}}});
 const filename=$derived(client==='opencode'?'opencode.json':client==='claude'?'Terminal · current session':'Terminal · streaming request');
 const snippet=$derived.by(()=>{
  if(client==='opencode')return JSON.stringify(config,null,2);
  if(client==='claude')return `read -rsp 'Local Bridge key: ' ANTHROPIC_AUTH_TOKEN; echo\nexport ANTHROPIC_AUTH_TOKEN\nexport ANTHROPIC_BASE_URL='${endpoint}'\nexport ANTHROPIC_MODEL='${model}'\nexport ANTHROPIC_DEFAULT_HAIKU_MODEL='${model}'\nexport ANTHROPIC_DEFAULT_SONNET_MODEL='${model}'\nexport ANTHROPIC_DEFAULT_OPUS_MODEL='${model}'\nclaude`;
  const path=client==='chat'?'/v1/chat/completions':client==='responses'?'/v1/responses':'/v1/messages';
  const payload=client==='responses'?{model,input:'Explain how you will approach a code review.',stream:true}:client==='messages'?{model,max_tokens:1024,stream:true,messages:[{role:'user',content:'Explain how you will approach a code review.'}]}:{model,stream:true,messages:[{role:'user',content:'Explain how you will approach a code review.'}]};
  return `read -rsp 'Local Bridge key: ' BRIDGE_API_KEY; echo\nexport BRIDGE_API_KEY\ncurl --no-buffer '${endpoint}${path}' \\\n  -H "Authorization: Bearer $BRIDGE_API_KEY" \\\n  -H 'Content-Type: application/json' \\\n  -H 'X-Bridge-Session: terminal-review' \\\n${client==='messages'?"  -H 'anthropic-version: 2023-06-01' \\\n":''}  --data '${JSON.stringify(payload)}'`;
 });
 async function reveal(){if(app.secret){app.secret='';clearTimeout(timer);return;}const result=await app.perform<{token:string}>('key.reveal');if(result){app.secret=result.token;clearTimeout(timer);timer=setTimeout(()=>app.secret='',30000);}}
 async function copyKey(){const result=await app.perform<{token:string}>('key.reveal');if(result)await app.clipboard(result.token);}
 async function probe(){probing=true;probeMessage='';try{const result=await bridge.probe();probeMessage=`HTTP /health answered in ${result.round_trip_ms} ms. Zag protocol 1 confirmed.`;}catch(error){app.error=String(error);}finally{probing=false;}}
 onDestroy(()=>{clearTimeout(timer);app.secret='';});
</script>
<div class="split"><div>
 <section class="section"><div class="section-title"><h2>Connection details</h2><span class="tag" class:ready={app.snapshot?.api.running}><span class="dot" class:online={app.snapshot?.api.running}></span>{app.snapshot?.api.running?'Listening on loopback':'Stopped'}</span></div><label class="field"><span>OpenAI-compatible base URL</span><div class="readout"><Icon name="globe" size={15}/><code>{endpoint}/v1</code><button class="icon-button" aria-label="Copy API endpoint" onclick={()=>app.clipboard(`${endpoint}/v1`)}><Icon name="copy" size={14}/></button></div></label><div class="field"><span>Local API key <span class="faint">Not a provider credential</span></span><div class="readout"><Icon name="key" size={15}/><code>{app.secret||'sk-local-••••••••••••••••••••••••••••'}</code><button class="icon-button" aria-label={app.secret?'Hide API key':'Reveal API key'} disabled={!app.ready} onclick={reveal}><Icon name={app.secret?'close':'eye'} size={15}/></button><button class="icon-button" aria-label="Copy API key" disabled={!app.ready} onclick={copyKey}><Icon name="copy" size={14}/></button></div><span class="field-hint">Revealed keys disappear after 30 seconds. Copying is an explicit action.</span></div><label class="field" style="margin-bottom:0"><span>Model</span><select aria-label="Client model" bind:value={selected} disabled={!app.models.length}><option value="">{app.preferences.default_model?'Workspace default':'First discovered model'}</option>{#each app.models as m(m.id)}<option value={m.id}>{m.provider.label} / {m.display_name}</option>{/each}</select></label>{#if probeMessage}<div class="note good"><Icon name="check" size={15}/><span>{probeMessage} This does not send a prompt to a website.</span></div>{/if}</section>
 <section class="section" style="border:0"><div class="section-title"><h2>Client configuration</h2>{#if client==='opencode'}<button class="text-button" disabled={!app.models.length} onclick={()=>app.export('opencode.json',config)}><Icon name="download" size={14}/>Save config</button>{/if}</div><div class="segmented" aria-label="Client format">{#each clients as c}<button class:active={client===c.id} onclick={()=>client=c.id}>{c.name}</button>{/each}</div><div class="code-panel"><div class="code-heading"><Icon name={client==='opencode'?'folder':'terminal'} size={13}/><span>{filename}</span><button class="text-button" disabled={!app.models.length} onclick={()=>app.clipboard(snippet)}><Icon name="copy" size={13}/>Copy</button></div><pre>{snippet}</pre></div>{#if client==='opencode'}<p class="field-hint" style="margin-top:12px">Save in your project. Set <code>BRIDGE_API_KEY</code> in the terminal before launching OpenCode, or connect provider <code>bridge</code> through its credential manager. Model limits are omitted when unknown.</p>{:else if client==='claude'}<p class="field-hint" style="margin-top:12px">This sets the Messages gateway for this terminal only. Real Claude Code compatibility still depends on the selected website model and the client’s protocol requirements; it is not a vendor-supported non-Claude integration.</p>{:else}<p class="field-hint" style="margin-top:12px">Reuse the session header for continuation. Chat and Messages clients resend the ordered conversation; Responses clients can send <code>previous_response_id</code>. Never share the local key.</p>{/if}</section>
 </div><aside>
 <section class="section"><span class="label">Three steps, no new account</span><div class="step"><span class="step-num">1</span><div><strong>Open your AI website</strong><p>Sign in and select the model on its own page. Open its model menu to help discovery.</p></div></div><div class="step"><span class="step-num">2</span><div><strong>Pair your external coding tool</strong><p>These details connect the tool to this desktop app. They do not connect to a paid provider API.</p></div></div><div class="step"><span class="step-num">3</span><div><strong>Start a conversation</strong><p>Keep Bridge running. Requests stream through the corresponding website tab.</p></div></div></section><section class="section"><h3 style="margin-bottom:12px">What crosses the bridge</h3><p>Messages, model selections, framed tool calls, and cancellation. Website login credentials stay in the webview.</p><p style="margin-top:12px">The coding client executes tools. Bridge never executes a model’s shell command itself.</p></section><section class="section"><div class="note" style="padding:0"><Icon name="shield" size={16}/><span>Website limits and access rules still apply. Fallback is disabled unless you explicitly configure it.</span></div></section><button class="text-button" style="margin-top:15px" onclick={()=>app.navigate('sessions')}>Watch session activity<Icon name="arrow" size={13}/></button>
 </aside></div>

